resolver: lts-19.33

packages:
- xmonad
- xmonad-contrib
- xmonad-mycfg
# - xmobar

# flags:
  #xmobar:
    #all_extensions: true

# extra-deps:
# - netlink-1.1.1.0
# - libmpd-0.9.2.0

nix:
  packages:
    - xorg.libX11
    - xorg.libXext
    - xorg.libXft
    - xorg.libXpm
    - xorg.libXrandr
    - xorg.libXScrnSaver
    - zlib
    - pkgconfig
    # - alsaLib
    # - wirelesstools
