name: xmonad-mycfg

dependencies:
- base >= 4.7
- containers
- xmonad >= 0.17.0.9
- xmonad-contrib >= 0.17.0.9

library:
  source-dirs: src

executables:
  xmonad-mycfg-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - xmonad-mycfg
